package com.merge.backend.assessment.domain;

import com.merge.backend.identity.domain.Student;
import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.List;

@Entity
@Table(name = "build_comprehension_checks")
@Data
@NoArgsConstructor
public class BuildComprehensionCheck {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "build_submission_id", nullable = false)
    private BuildSubmission buildSubmission;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "student_id", nullable = false)
    private Student student;

    /**
     * Questions generated by AI-10: grounded in the student's specific code,
     * architecture document, and test strategies. Unanswerable without reading this exact work.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "questions", nullable = false, columnDefinition = "jsonb")
    private List<String> questions;

    @Column(name = "triggered_at", nullable = false)
    private Instant triggeredAt;

    /**
     * Server-enforced deadline: triggeredAt + (questions.size() × 10 seconds).
     * Client timer is purely visual; this is the authoritative cutoff.
     */
    @Column(name = "server_deadline", nullable = false)
    private Instant serverDeadline;

    /** Null until the student submits answers. */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "answers", columnDefinition = "jsonb")
    private List<String> answers;

    @Column(name = "submitted_at")
    private Instant submittedAt;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 10)
    private BuildComprehensionCheckStatus status = BuildComprehensionCheckStatus.PENDING;
}
